#!/bin/sh

CACHE_DIR="/opt/amazon/cache"

export AWS_ACCESS_KEY=${AWS_ACCESS_KEY:-'AWS_ACCESS_KEY_HERE'}
export AWS_SECRET_KEY=${AWS_SECRET_KEY:-'AWS_SECRET_KEY_HERE'}
export JAVA_HOME=${JAVA_HOME:-$(readlink -f /usr/bin/java | sed "s:bin/java::")}
export EC2_HOME=${EC2_HOME:-'/opt/amazon/src/ec2-api-tools/'};

export PATH="$PATH:${EC2_HOME}/bin/"

EC2_AVAILABILITY_ZONE=$(wget -qO- instance-data/latest/meta-data/placement/availability-zone)
EC2_REGION=$(expr match $EC2_AVAILABILITY_ZONE '\(.*\).')

if [ ! -d "$CACHE_DIR" ]; then
    mkdir -p "$CACHE_DIR";
fi

# Clean cache
if [ -n "$CACHE_DIR" ]; then
    find "$CACHE_DIR" -type f -mmin +360 -delete
fi;

if [ ! -e "$CACHE_DIR/roles" ]; then

  roles=$(ec2-describe-tags \
    --region "${EC2_REGION}" \
    --filter "resource-id=$(facter ec2_instance_id)" \
    --filter "resource-type=instance" \
    --filter "key=Roles" | cut -f5
  );

  if [ -n "$roles" ]; then
    echo "$roles" > "$CACHE_DIR/roles";
  fi

fi

if [ -e "$CACHE_DIR/roles" ]; then
    printf "%20s ROLE %20s\n" |tr " " "=";
    cat "$CACHE_DIR/roles";
    printf "%46s\n\n" |tr " " "="
fi;

